# Generated by Django 3.1.2 on 2020-11-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0002_theme_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
