# Generated by Django 3.1.2 on 2020-11-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0004_cours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name_plural': 'cours'},
        ),
        migrations.AddField(
            model_name='theme',
            name='descriptif',
            field=models.TextField(blank=True),
        ),
    ]
