# Generated by Django 3.1.3 on 2020-11-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0005_auto_20201113_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Td',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsi.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsi.theme')),
            ],
        ),
    ]
