# Generated by Django 3.1.3 on 2020-11-19 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nsi', '0006_question_td'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='td',
            options={'verbose_name': 'TD', 'verbose_name_plural': 'travaux dirigés'},
        ),
        migrations.AddField(
            model_name='cours',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
