# Generated by Django 3.1.3 on 2020-11-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0008_question_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='td',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Qcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(to='nsi.Question')),
            ],
        ),
    ]
