# Generated by Django 3.1.3 on 2020-11-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0009_auto_20201127_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsi.theme'),
        ),
    ]
