# Generated by Django 3.1.3 on 2020-11-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0010_qcm_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='imageURL',
            field=models.URLField(blank=True),
        ),
    ]
