# Generated by Django 3.1.3 on 2020-12-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0013_auto_20201213_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='short_name',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
