# Generated by Django 3.1.3 on 2020-12-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0015_auto_20201213_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='short_name',
        ),
    ]
