# Generated by Django 3.1.3 on 2020-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0021_auto_20201225_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
