# Generated by Django 3.1.3 on 2021-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0022_theme_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='td',
            name='contenu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
